# A triangle number is generated by adding successive natural numbers. For instance: the seventh triangle number is 1+2+3+4+5+6+7=28. This triangle number has six divisors: 1,2,4,5,14,28. Find the first triangle number to have over 500 divisors.

divisor_threshold = 500
triangle_number = 1 # Initial

